version: '3'
name: rcdoc

services:

  nginx:
      image: nginx:1.25-alpine
      ports:
        - 80:80
      volumes:
        - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      depends_on:
        - frontend
        - backend

  frontend:
    build:
      context: ./front/
      target: final
      args:
        # IF YOU WANT TO CHANGE THE API LOCATION, CHANGE THE LINE BELOW
        VITE_API_LOC: "api.localhost" 

  # Backend and all it's dependencies
  backend:
    build:
      context: ./back/
      target: final
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    links:
      - redis
      - postgres
    env_file:
      - ./env/backend.properties

  redis:
    image: "redis:alpine"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 2s
      retries: 10

    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    volumes:  
      - "./config/redis:/usr/local/etc/redis:ro"
  
  postgres:
    restart: always
    image: "postgres:alpine"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 1s
      timeout: 2s
      retries: 10

    volumes:
      - "pg_data:/var/lib/postgresql/data"
    env_file:
      - ./env/postgres.properties
    user: postgres

volumes:
  pg_data: {}

